### ISSUE TITLE
wiki [舰船]，后台报错。机器人无反馈

### ISSUE THREAD

**Issue by Testplayers** [DK09/blhx-wiki-mirai-plugin#7]
2022-05-13 00:08:33 W/stderr: java.io.FileNotFoundException: D:\BOTS\data\org.ir
is.wiki\out\ship\新泽西（花园）.png (系统找不到指定的路径。)
2022-05-13 00:08:33 W/stderr:   at java.base/java.io.RandomAccessFile.open0(Nati
ve Method)
2022-05-13 00:08:33 W/stderr:   at java.base/java.io.RandomAccessFile.open(Unkno
wn Source)
2022-05-13 00:08:33 W/stderr:   at java.base/java.io.RandomAccessFile.<init>(Unk
nown Source)
2022-05-13 00:08:33 W/stderr:   at java.base/java.io.RandomAccessFile.<init>(Unk
nown Source)
2022-05-13 00:08:33 W/stderr:   at java.desktop/javax.imageio.stream.FileImageOu
tputStream.<init>(Unknown Source)
2022-05-13 00:08:33 W/stderr:   at java.desktop/com.sun.imageio.spi.FileImageOut
putStreamSpi.createOutputStreamInstance(Unknown Source)
2022-05-13 00:08:33 W/stderr:   at java.desktop/javax.imageio.ImageIO.createImag
eOutputStream(Unknown Source)
2022-05-13 00:08:33 W/stderr:   at java.desktop/javax.imageio.ImageIO.write(Unkn
own Source)
2022-05-13 00:08:33 W/stderr:   at org.iris.wiki.data.ShipAttrData.toMessage(Shi
pAttrData.kt:267)
2022-05-13 00:08:33 W/stderr:   at org.iris.wiki.utils.MessageBuildUtils.build(M
essageBuildUtils.kt:26)
2022-05-13 00:08:33 W/stderr:   at org.iris.wiki.Listener.wiki(Listener.kt:82)
2022-05-13 00:08:33 W/stderr:   at org.iris.wiki.Listener$subscribe$1.invokeSusp
end(Listener.kt:43)
2022-05-13 00:08:33 W/stderr:   at org.iris.wiki.Listener$subscribe$1.invoke(Lis
tener.kt)
2022-05-13 00:08:33 W/stderr:   at org.iris.wiki.Listener$subscribe$1.invoke(Lis
tener.kt)
2022-05-13 00:08:33 W/stderr:   at net.mamoe.mirai.event.EventChannel$subscribeA
lways$1.invokeSuspend(EventChannel.kt:455)
2022-05-13 00:08:33 W/stderr:   at net.mamoe.mirai.event.EventChannel$subscribeA
lways$1.invoke(EventChannel.kt)
2022-05-13 00:08:33 W/stderr:   at net.mamoe.mirai.event.EventChannel$subscribeA
lways$1.invoke(EventChannel.kt)
2022-05-13 00:08:33 W/stderr:   at net.mamoe.mirai.internal.event.Handler$onEven
t$2.invokeSuspend(InternalEventListeners.kt:50)
2022-05-13 00:08:33 W/stderr:   at net.mamoe.mirai.internal.event.Handler$onEven
t$2.invoke(InternalEventListeners.kt)
2022-05-13 00:08:33 W/stderr:   at net.mamoe.mirai.internal.event.Handler$onEven
t$2.invoke(InternalEventListeners.kt)
2022-05-13 00:08:33 W/stderr:   at kotlinx.coroutines.intrinsics.UndispatchedKt.
startUndispatchedOrReturn(Undispatched.kt:89)
2022-05-13 00:08:33 W/stderr:   at kotlinx.coroutines.BuildersKt__Builders_commo
nKt.withContext(Builders.common.kt:165)
2022-05-13 00:08:33 W/stderr:   at kotlinx.coroutines.BuildersKt.withContext(Unk
nown Source)
2022-05-13 00:08:33 W/stderr:   at net.mamoe.mirai.internal.event.Handler.onEven
t(InternalEventListeners.kt:50)
2022-05-13 00:08:33 W/stderr:   at net.mamoe.mirai.internal.event.InternalEventL
istenersKt.process(InternalEventListeners.kt:166)
2022-05-13 00:08:33 W/stderr:   at net.mamoe.mirai.internal.event.InternalEventL
istenersKt.callAndRemoveIfRequired(InternalEventListeners.kt:115)
2022-05-13 00:08:33 W/stderr:   at net.mamoe.mirai.event._EventBroadcast.broadca
stImpl(Event.kt:174)
2022-05-13 00:08:33 W/stderr:   at net.mamoe.mirai.IMirai.broadcastEvent(IMirai.
kt:318)
2022-05-13 00:08:33 W/stderr:   at net.mamoe.mirai.internal.MiraiImpl.broadcastE
vent$suspendImpl(MiraiImpl.kt:308)
2022-05-13 00:08:33 W/stderr:   at net.mamoe.mirai.internal.MiraiImpl.broadcastE
vent(MiraiImpl.kt)
2022-05-13 00:08:33 W/stderr:   at net.mamoe.mirai.event._EventBroadcast.broadca
stPublic$suspendImpl(Event.kt:161)
2022-05-13 00:08:33 W/stderr:   at net.mamoe.mirai.event._EventBroadcast.broadca
stPublic(Event.kt)
2022-05-13 00:08:33 W/stderr:   at net.mamoe.mirai.event.EventKt.broadcast(Event
.kt:146)
2022-05-13 00:08:33 W/stderr:   at net.mamoe.mirai.internal.network.components.E
ventDispatcherImpl$broadcast$2.invokeSuspend(EventDispatcher.kt:90)
2022-05-13 00:08:33 W/stderr:   at net.mamoe.mirai.internal.network.components.E
ventDispatcherImpl$broadcast$2.invoke(EventDispatcher.kt)
2022-05-13 00:08:33 W/stderr:   at net.mamoe.mirai.internal.network.components.E
ventDispatcherImpl$broadcast$2.invoke(EventDispatcher.kt)
2022-05-13 00:08:33 W/stderr:   at kotlinx.coroutines.intrinsics.UndispatchedKt.
startUndispatchedOrReturn(Undispatched.kt:89)
2022-05-13 00:08:33 W/stderr:   at kotlinx.coroutines.BuildersKt__Builders_commo
nKt.withContext(Builders.common.kt:165)
2022-05-13 00:08:33 W/stderr:   at kotlinx.coroutines.BuildersKt.withContext(Unk
nown Source)
2022-05-13 00:08:33 W/stderr:   at net.mamoe.mirai.internal.network.components.E
ventDispatcherImpl.broadcast$suspendImpl(EventDispatcher.kt:89)
2022-05-13 00:08:33 W/stderr:   at net.mamoe.mirai.internal.network.components.E
ventDispatcherImpl.broadcast(EventDispatcher.kt)
2022-05-13 00:08:33 W/stderr:   at net.mamoe.mirai.internal.network.components.E
ventDispatcherImpl$broadcastAsync$job$1.invokeSuspend(EventDispatcher.kt:105)
2022-05-13 00:08:33 W/stderr:   at net.mamoe.mirai.internal.network.components.E
ventDispatcherImpl$broadcastAsync$job$1.invoke(EventDispatcher.kt)
2022-05-13 00:08:33 W/stderr:   at net.mamoe.mirai.internal.network.components.E
ventDispatcherImpl$broadcastAsync$job$1.invoke(EventDispatcher.kt)
2022-05-13 00:08:33 W/stderr:   at kotlinx.coroutines.intrinsics.UndispatchedKt.
startCoroutineUndispatched(Undispatched.kt:55)
2022-05-13 00:08:33 W/stderr:   at kotlinx.coroutines.CoroutineStart.invoke(Coro
utineStart.kt:112)
2022-05-13 00:08:33 W/stderr:   at kotlinx.coroutines.AbstractCoroutine.start(Ab
stractCoroutine.kt:126)
2022-05-13 00:08:33 W/stderr:   at kotlinx.coroutines.BuildersKt__Builders_commo
nKt.launch(Builders.common.kt:56)
2022-05-13 00:08:33 W/stderr:   at kotlinx.coroutines.BuildersKt.launch(Unknown
Source)
2022-05-13 00:08:33 W/stderr:   at net.mamoe.mirai.internal.network.components.E
ventDispatcherImpl.broadcastAsync-kKe4JaQ(EventDispatcher.kt:102)
2022-05-13 00:08:33 W/stderr:   at net.mamoe.mirai.internal.network.components.E
ventDispatcher.broadcastAsync-kKe4JaQ$default(EventDispatcher.kt:35)
2022-05-13 00:08:33 W/stderr:   at net.mamoe.mirai.internal.network.components.E
ventBroadcasterPacketHandler.impl(PacketHandler.kt:87)
2022-05-13 00:08:33 W/stderr:   at net.mamoe.mirai.internal.network.components.E
ventBroadcasterPacketHandler.handlePacket(PacketHandler.kt:73)
2022-05-13 00:08:33 W/stderr:   at net.mamoe.mirai.internal.network.components.P
acketHandlerChain.handlePacket(PacketHandler.kt:42)
2022-05-13 00:08:33 W/stderr:   at net.mamoe.mirai.internal.network.handler.Netw
orkHandlerSupport$collectReceived$3.invokeSuspend(NetworkHandlerSupport.kt:84)
2022-05-13 00:08:33 W/stderr:   at net.mamoe.mirai.internal.network.handler.Netw
orkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
2022-05-13 00:08:33 W/stderr:   at net.mamoe.mirai.internal.network.handler.Netw
orkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
2022-05-13 00:08:33 W/stderr:   at kotlinx.coroutines.intrinsics.UndispatchedKt.
startCoroutineUndispatched(Undispatched.kt:55)
2022-05-13 00:08:33 W/stderr:   at kotlinx.coroutines.CoroutineStart.invoke(Coro
utineStart.kt:112)
2022-05-13 00:08:33 W/stderr:   at kotlinx.coroutines.AbstractCoroutine.start(Ab
stractCoroutine.kt:126)
2022-05-13 00:08:33 W/stderr:   at kotlinx.coroutines.BuildersKt__Builders_commo
nKt.launch(Builders.common.kt:56)
2022-05-13 00:08:33 W/stderr:   at kotlinx.coroutines.BuildersKt.launch(Unknown
Source)
2022-05-13 00:08:33 W/stderr:   at kotlinx.coroutines.BuildersKt__Builders_commo
nKt.launch$default(Builders.common.kt:47)
2022-05-13 00:08:33 W/stderr:   at kotlinx.coroutines.BuildersKt.launch$default(
Unknown Source)
2022-05-13 00:08:33 W/stderr:   at net.mamoe.mirai.internal.network.handler.Netw
orkHandlerSupport.collectReceived$mirai_core(NetworkHandlerSupport.kt:82)
2022-05-13 00:08:33 W/stderr:   at net.mamoe.mirai.internal.network.impl.netty.N
ettyNetworkHandler$PacketDecodePipeline$send$1.invokeSuspend(NettyNetworkHandler
.kt:178)
2022-05-13 00:08:33 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuati
onImpl.resumeWith(ContinuationImpl.kt:33)
2022-05-13 00:08:33 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(Dispatc
hedTask.kt:106)
2022-05-13 00:08:33 W/stderr:   at io.netty.util.concurrent.AbstractEventExecuto
r.safeExecute(AbstractEventExecutor.java:164)
2022-05-13 00:08:33 W/stderr:   at io.netty.util.concurrent.SingleThreadEventExe
cutor.runAllTasks(SingleThreadEventExecutor.java:472)
2022-05-13 00:08:33 W/stderr:   at io.netty.channel.nio.NioEventLoop.run(NioEven
tLoop.java:497)
2022-05-13 00:08:33 W/stderr:   at io.netty.util.concurrent.SingleThreadEventExe
cutor$4.run(SingleThreadEventExecutor.java:989)
2022-05-13 00:08:33 W/stderr:   at io.netty.util.internal.ThreadExecutorMap$2.ru
n(ThreadExecutorMap.java:74)
2022-05-13 00:08:33 W/stderr:   at io.netty.util.concurrent.FastThreadLocalRunna
ble.run(FastThreadLocalRunnable.java:30)
2022-05-13 00:08:33 W/stderr:   at java.base/java.lang.Thread.run(Unknown Source
)
2022-05-13 00:08:33 E/blhx-wiki: Exception in coroutine Listener of blhx-wiki
javax.imageio.IIOException: Can't create an ImageOutputStream!
        at java.desktop/javax.imageio.ImageIO.write(Unknown Source)
        at org.iris.wiki.data.ShipAttrData.toMessage(ShipAttrData.kt:267)
        at org.iris.wiki.utils.MessageBuildUtils.build(MessageBuildUtils.kt:26)
        at org.iris.wiki.Listener.wiki(Listener.kt:82)
        at org.iris.wiki.Listener$subscribe$1.invokeSuspend(Listener.kt:43)
        at org.iris.wiki.Listener$subscribe$1.invoke(Listener.kt)
        at org.iris.wiki.Listener$subscribe$1.invoke(Listener.kt)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invokeSuspend(Ev
entChannel.kt:455)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChan
nel.kt)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChan
nel.kt)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invokeSuspend(Intern
alEventListeners.kt:50)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEvent
Listeners.kt)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEvent
Listeners.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrRetur
n(Undispatched.kt:89)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders
.common.kt:165)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.internal.event.Handler.onEvent(InternalEventListeners
.kt:50)
        at net.mamoe.mirai.internal.event.InternalEventListenersKt.process(Inter
nalEventListeners.kt:166)
        at net.mamoe.mirai.internal.event.InternalEventListenersKt.callAndRemove
IfRequired(InternalEventListeners.kt:115)
        at net.mamoe.mirai.event._EventBroadcast.broadcastImpl(Event.kt:174)
        at net.mamoe.mirai.IMirai.broadcastEvent(IMirai.kt:318)
        at net.mamoe.mirai.internal.MiraiImpl.broadcastEvent$suspendImpl(MiraiIm
pl.kt:308)
        at net.mamoe.mirai.internal.MiraiImpl.broadcastEvent(MiraiImpl.kt)
        at net.mamoe.mirai.event._EventBroadcast.broadcastPublic$suspendImpl(Eve
nt.kt:161)
        at net.mamoe.mirai.event._EventBroadcast.broadcastPublic(Event.kt)
        at net.mamoe.mirai.event.EventKt.broadcast(Event.kt:146)
        at net.mamoe.mirai.internal.network.components.EventDispatcherImpl$broad
cast$2.invokeSuspend(EventDispatcher.kt:90)
        at net.mamoe.mirai.internal.network.components.EventDispatcherImpl$broad
cast$2.invoke(EventDispatcher.kt)
        at net.mamoe.mirai.internal.network.components.EventDispatcherImpl$broad
cast$2.invoke(EventDispatcher.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrRetur
n(Undispatched.kt:89)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders
.common.kt:165)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.internal.network.components.EventDispatcherImpl.broad
cast$suspendImpl(EventDispatcher.kt:89)
        at net.mamoe.mirai.internal.network.components.EventDispatcherImpl.broad
cast(EventDispatcher.kt)
        at net.mamoe.mirai.internal.network.components.EventDispatcherImpl$broad
castAsync$job$1.invokeSuspend(EventDispatcher.kt:105)
        at net.mamoe.mirai.internal.network.components.EventDispatcherImpl$broad
castAsync$job$1.invoke(EventDispatcher.kt)
        at net.mamoe.mirai.internal.network.components.EventDispatcherImpl$broad
castAsync$job$1.invoke(EventDispatcher.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatch
ed(Undispatched.kt:55)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.comm
on.kt:56)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
        at net.mamoe.mirai.internal.network.components.EventDispatcherImpl.broad
castAsync-kKe4JaQ(EventDispatcher.kt:102)
        at net.mamoe.mirai.internal.network.components.EventDispatcher.broadcast
Async-kKe4JaQ$default(EventDispatcher.kt:35)
        at net.mamoe.mirai.internal.network.components.EventBroadcasterPacketHan
dler.impl(PacketHandler.kt:87)
        at net.mamoe.mirai.internal.network.components.EventBroadcasterPacketHan
dler.handlePacket(PacketHandler.kt:73)
        at net.mamoe.mirai.internal.network.components.PacketHandlerChain.handle
Packet(PacketHandler.kt:42)
        at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collec
tReceived$3.invokeSuspend(NetworkHandlerSupport.kt:84)
        at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collec
tReceived$3.invoke(NetworkHandlerSupport.kt)
        at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collec
tReceived$3.invoke(NetworkHandlerSupport.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatch
ed(Undispatched.kt:55)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.comm
on.kt:56)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Build
ers.common.kt:47)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
        at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.collec
tReceived$mirai_core(NetworkHandlerSupport.kt:82)
        at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$Packe
tDecodePipeline$send$1.invokeSuspend(NettyNetworkHandler.kt:178)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Contin
uationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEv
entExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(Single
ThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThread
EventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java
:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalR
unnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by DK09** [comment]
已修复，请下载最新的jar包

**Comment by DK09** [comment]
这个bug不影响使用，有些 @用户 的消息能触发

**Comment by Testplayers** [comment]
好的，非常感谢！
